platform :ios, '13.0'
use_frameworks!

target 'demo' do

#  pod 'TipTopPay', :git =>  "https://github.com/tiptoppaymobile/TipTopPay-SDK-iOS", :branch => "master"
#  pod 'TipTopPayNetworking', :git =>  "https://github.com/tiptoppaymobile/TipTopPay-SDK-iOS", :branch => "master"

  pod 'TipTopPay', :path => "../sdk"
  pod 'TipTopPayNetworking', :path => "../networking"
  
end
