platform :ios, '13.0'
use_frameworks!

target 'demo' do

#  pod 'TipTopPay', :git =>  "https://gitlab.com/tiptoppay/mobile/tiptoppay-sdk-ios", :branch => "master"
#  pod 'TipTopPayNetworking', :git =>  "https://gitlab.com/tiptoppay/mobile/tiptoppay-sdk-ios", :branch => "master"

  pod 'TipTopPay', :path => "../sdk"
  pod 'TipTopPayNetworking', :path => "../networking"
  
end
